- name: Create concourse directory
  become: true
  file:
    state: directory
    path: /var/lib/concourse-web
  
- name: Create concourse keys directory
  become: true
  file:
    state: directory
    path: /var/lib/concourse-web/keys

- name: Generate session_signing_key
  shell: ssh-keygen -t rsa -b 4096 -m PEM -f /var/lib/concourse-web/keys/session_signing_key -N ''
  args:
    creates: /var/lib/concourse-web/keys/session_signing_key

- name: Generate tsa_host_key
  shell: ssh-keygen -t rsa -b 4096 -m PEM -f /var/lib/concourse-web/keys/tsa_host_key -N ''
  args:
    creates: /var/lib/concourse-web/keys/tsa_host_key

- name: Create concourse keys directory
  become: true
  file:
    state: directory
    path: /var/lib/concourse-worker/keys
  delegate_to: "{{ item }}"
  loop: "{{ groups['concourse-worker'] }}"

- name: Generate worker_key
  shell: ssh-keygen -t rsa -b 4096 -m PEM -f /var/lib/concourse-worker/keys/worker_key -N ''
  args:
    creates: /var/lib/concourse-worker/keys/worker_key
  delegate_to: "{{ item }}"
  loop: "{{ groups['concourse-worker'] }}"

- name: Get worker keys
  slurp:
    src: /var/lib/concourse-worker/keys/worker_key.pub
  delegate_to: "{{ item }}"
  loop: "{{ groups['concourse-worker'] }}"
  register: worker_keys

- name: Create authorized_worker_keys.pub
  template:
    src: authorized_worker_keys.pub
    dest: /var/lib/concourse-web/keys

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /var/lib/concourse-web

- name: Copy nginx config
  become: true
  copy:
    src: ci.engiqueer.net
    dest: /etc/nginx/sites-enabled/
  notify:
    - Restart nginx

- name: Start concourse
  community.docker.docker_compose_v2:
    project_src: /var/lib/concourse-web
    